@baseUrl = http://localhost:4000
### short crypto list
GET {{baseUrl}}/cmc/coins/short HTTP/1.1
### rekorbit main data list
POST {{baseUrl}}/rekorbit/maindata HTTP/1.1
Content-Type: 	application/json; charset=utf-8

["LTC", "BTC", "ETH", "BCH", "XRP"]
### cmc assets list
GET {{baseUrl}}/cmc/coins HTTP/1.1
### cmc assets detail
GET {{baseUrl}}/cmc/coins/bitcoin HTTP/1.1
### dtoday api
GET {{baseUrl}}/calc/dolartoday HTTP/1.1
### dtoday detail api
GET {{baseUrl}}/calc/dolartoday/euro HTTP/1.1
### localbitcoins trader

GET {{baseUrl}}/localbtc/trader/Top-BTC HTTP/1.1
content-type: application/json
### localbitcoins api
PUT {{baseUrl}}/localbtc/tradingPosts/currency/ves HTTP/1.1
content-type: application/json

{"type":"buy","location":"ve","page":2,"amount":1000000,"bank":""}

### localbitcoins find by trader posts
PUT {{baseUrl}}/localbtc/traderPosts/location/es HTTP/1.1
content-type: application/json

{"type":"buy","trader":"Top-BTC"}

### testing original localbitcoins endpoints
GET https://localbitcoins.com/buy-bitcoins-online/es/spain/.json?page=1

### ARS Currency
GET {{baseUrl}}/calc/arsinfo HTTP/1.1